name: Label PRs
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const repos = await github.rest.pulls.list({
                ...context.repo
            })
            console.log(repos)
