name: Tag Conflicts
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const repos = (await github.rest.pulls.list({
                ...context.repo
            })).data
            const promises = repos.map(repo => {
                const { number } = repo
                return github.rest.pulls.get({
                    ...context.repo,
                    pull_number: number
                })
            })
            const prs = await Promise.allSettled(promises)
            prs.forEach(pr => {
                console.log(pr.value.data.mergeable)
                if (pr.value.data.mergeable === false) {
                    github.rest.issues.addLabels({
                        ...context.repo,
                        issue_number: pr.value.data.number,
                        labels: ["merge conflict"]
                    })
                }
            })
